// Auto-generated by tools/gen_parser_vectors.py. Do not edit directly.
#pragma once

#include <stddef.h>
#include <stdint.h>
#include "vhttp_parser.h"

typedef struct {
    const char *name;
    const char *value;
} vhttp_expect_header_t;

typedef struct {
    const char *key;
    const char *value;
    uint8_t has_value;
} vhttp_expect_query_t;

typedef struct {
    const char *name;
    const char *raw;
    size_t raw_len;
    vhttp_parse_result_t result;
    const char *method;
    const char *uri;
    const char *path;
    const char *query;
    const vhttp_expect_header_t *headers;
    size_t num_headers;
    const vhttp_expect_query_t *query_params;
    size_t num_query_params;
    uint32_t content_length;
    uint8_t is_chunked;
    uint8_t is_websocket;
    const char *body;
    size_t body_len;
} vhttp_test_case_t;

static const vhttp_expect_header_t headers_get_root[] = {
    { "Host", "example.com" },
};

static const vhttp_expect_header_t headers_get_query_params[] = {
    { "Host", "example.com" },
};
static const vhttp_expect_query_t query_get_query_params[] = {
    { "q", "esp32", 1 },
    { "lang", "en", 1 },
    { "flag", "", 0 },
    { "empty", "", 1 },
};

static const vhttp_expect_header_t headers_post_with_body[] = {
    { "Host", "example.com" },
    { "Content-Length", "11" },
};

static const vhttp_expect_header_t headers_websocket_upgrade[] = {
    { "Host", "example.com" },
    { "Upgrade", "WebSocket" },
    { "Connection", "Upgrade" },
};









static const vhttp_test_case_t vhttp_test_cases[] = {
    {
        "get_root",
        "GET / HTTP/1.1\r\nHost: example.com\r\n\r\n",
        37,
        VHTTP_PARSE_OK,
        "GET",
        "/",
        "/",
        "",
        headers_get_root,
        1,
        NULL,
        0,
        0,
        0,
        0,
        "",
        0,
    },
    {
        "get_query_params",
        "GET /search?q=esp32&lang=en&flag&empty= HTTP/1.1\r\nHost: example.com\r\n\r\n",
        71,
        VHTTP_PARSE_OK,
        "GET",
        "/search?q=esp32&lang=en&flag&empty=",
        "/search",
        "q=esp32&lang=en&flag&empty=",
        headers_get_query_params,
        1,
        query_get_query_params,
        4,
        0,
        0,
        0,
        "",
        0,
    },
    {
        "post_with_body",
        "POST /api/items HTTP/1.1\r\nHost: example.com\r\nContent-Length: 11\r\n\r\nhello=world",
        78,
        VHTTP_PARSE_OK,
        "POST",
        "/api/items",
        "/api/items",
        "",
        headers_post_with_body,
        2,
        NULL,
        0,
        11,
        0,
        0,
        "hello=world",
        11,
    },
    {
        "websocket_upgrade",
        "GET /ws HTTP/1.1\r\nHost: example.com\r\nUpgrade: WebSocket\r\nConnection: Upgrade\r\n\r\n",
        80,
        VHTTP_PARSE_OK,
        "GET",
        "/ws",
        "/ws",
        "",
        headers_websocket_upgrade,
        3,
        NULL,
        0,
        0,
        0,
        1,
        "",
        0,
    },
    {
        "chunked_unsupported",
        "POST /upload HTTP/1.1\r\nHost: example.com\r\nTransfer-Encoding: chunked\r\n\r\n4\r\ntest\r\n0\r\n\r\n",
        86,
        VHTTP_PARSE_UNSUPPORTED,
        "",
        "",
        "",
        "",
        NULL,
        0,
        NULL,
        0,
        0,
        0,
        0,
        "",
        0,
    },
    {
        "invalid_request_line",
        "GET /missing-version\r\nHost: example.com\r\n\r\n",
        43,
        VHTTP_PARSE_INVALID,
        "",
        "",
        "",
        "",
        NULL,
        0,
        NULL,
        0,
        0,
        0,
        0,
        "",
        0,
    },
    {
        "incomplete_headers",
        "GET / HTTP/1.1\r\nHost: example.com\r\n",
        35,
        VHTTP_PARSE_INCOMPLETE,
        "",
        "",
        "",
        "",
        NULL,
        0,
        NULL,
        0,
        0,
        0,
        0,
        "",
        0,
    },
    {
        "body_incomplete",
        "POST /submit HTTP/1.1\r\nHost: example.com\r\nContent-Length: 5\r\n\r\nabc",
        66,
        VHTTP_PARSE_INCOMPLETE,
        "",
        "",
        "",
        "",
        NULL,
        0,
        NULL,
        0,
        0,
        0,
        0,
        "",
        0,
    },
    {
        "too_many_headers",
        "GET / HTTP/1.1\r\nH01: v\r\nH02: v\r\nH03: v\r\nH04: v\r\nH05: v\r\nH06: v\r\nH07: v\r\nH08: v\r\nH09: v\r\nH10: v\r\nH11: v\r\nH12: v\r\nH13: v\r\nH14: v\r\nH15: v\r\nH16: v\r\nH17: v\r\nH18: v\r\nH19: v\r\nH20: v\r\nH21: v\r\nH22: v\r\nH23: v\r\nH24: v\r\nH25: v\r\n\r\n",
        218,
        VHTTP_PARSE_TOO_LARGE,
        "",
        "",
        "",
        "",
        NULL,
        0,
        NULL,
        0,
        0,
        0,
        0,
        "",
        0,
    },
    {
        "too_many_query_params",
        "GET /search?p1=v1&p2=v2&p3=v3&p4=v4&p5=v5&p6=v6&p7=v7&p8=v8&p9=v9&p10=v10&p11=v11&p12=v12&p13=v13&p14=v14&p15=v15&p16=v16&p17=v17 HTTP/1.1\r\nHost: example.com\r\n\r\n",
        161,
        VHTTP_PARSE_TOO_LARGE,
        "",
        "",
        "",
        "",
        NULL,
        0,
        NULL,
        0,
        0,
        0,
        0,
        "",
        0,
    },
    {
        "uri_too_long",
        "GET /aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa HTTP/1.1\r\nHost: example.com\r\n\r\n",
        549,
        VHTTP_PARSE_TOO_LARGE,
        "",
        "",
        "",
        "",
        NULL,
        0,
        NULL,
        0,
        0,
        0,
        0,
        "",
        0,
    },
    {
        "content_length_too_large",
        "POST /big HTTP/1.1\r\nHost: example.com\r\nContent-Length: 70000\r\n\r\n",
        64,
        VHTTP_PARSE_TOO_LARGE,
        "",
        "",
        "",
        "",
        NULL,
        0,
        NULL,
        0,
        0,
        0,
        0,
        "",
        0,
    },
};

static const size_t vhttp_test_case_count = sizeof(vhttp_test_cases) / sizeof(vhttp_test_cases[0]);

