// Auto-generated by tools/gen_router_vectors.py. Do not edit directly.
#pragma once

#include <stddef.h>
#include <stdint.h>
#include "vhttp_router.h"

typedef struct {
    const char *method;
    const char *pattern;
    uint16_t handler;
    vhttp_router_result_t result;
} vhttp_route_case_t;

typedef struct {
    const char *name;
    const char *value;
    vhttp_param_type_t type;
} vhttp_expect_param_t;

typedef struct {
    const char *method;
    const char *path;
    vhttp_router_result_t result;
    uint16_t handler;
    const vhttp_expect_param_t *params;
    size_t num_params;
} vhttp_query_case_t;

typedef struct {
    const char *name;
    const vhttp_route_case_t *routes;
    size_t num_routes;
    const vhttp_query_case_t *queries;
    size_t num_queries;
} vhttp_router_case_t;

static const vhttp_route_case_t routes_static_root[] = {
    { "GET", "/", 1, VHTTP_ROUTER_OK },
};

static const vhttp_query_case_t queries_static_root[] = {
    { "GET", "/", VHTTP_ROUTER_OK, 1, NULL, 0 },
};

static const vhttp_route_case_t routes_static_priority[] = {
    { "GET", "/files/new", 10, VHTTP_ROUTER_OK },
    { "GET", "/files/{name}", 11, VHTTP_ROUTER_OK },
};

static const vhttp_expect_param_t params_static_priority_1[] = {
    { "name", "old", VHTTP_PARAM_STR },
};

static const vhttp_query_case_t queries_static_priority[] = {
    { "GET", "/files/new", VHTTP_ROUTER_OK, 10, NULL, 0 },
    { "GET", "/files/old", VHTTP_ROUTER_OK, 11, params_static_priority_1, 1 },
};

static const vhttp_route_case_t routes_param_int[] = {
    { "GET", "/items/{id:int}", 20, VHTTP_ROUTER_OK },
};

static const vhttp_expect_param_t params_param_int_0[] = {
    { "id", "42", VHTTP_PARAM_INT },
};

static const vhttp_query_case_t queries_param_int[] = {
    { "GET", "/items/42", VHTTP_ROUTER_OK, 20, params_param_int_0, 1 },
    { "GET", "/items/abc", VHTTP_ROUTER_NOT_FOUND, 0, NULL, 0 },
};

static const vhttp_route_case_t routes_param_float[] = {
    { "GET", "/sensor/{value:float}", 30, VHTTP_ROUTER_OK },
};

static const vhttp_expect_param_t params_param_float_0[] = {
    { "value", "12.5", VHTTP_PARAM_FLOAT },
};

static const vhttp_expect_param_t params_param_float_1[] = {
    { "value", "-7", VHTTP_PARAM_FLOAT },
};

static const vhttp_query_case_t queries_param_float[] = {
    { "GET", "/sensor/12.5", VHTTP_ROUTER_OK, 30, params_param_float_0, 1 },
    { "GET", "/sensor/-7", VHTTP_ROUTER_OK, 30, params_param_float_1, 1 },
};

static const vhttp_route_case_t routes_param_path[] = {
    { "GET", "/static/{path:path}", 40, VHTTP_ROUTER_OK },
};

static const vhttp_expect_param_t params_param_path_0[] = {
    { "path", "js/app.js", VHTTP_PARAM_PATH },
};

static const vhttp_query_case_t queries_param_path[] = {
    { "GET", "/static/js/app.js", VHTTP_ROUTER_OK, 40, params_param_path_0, 1 },
};

static const vhttp_route_case_t routes_conflict_param_name[] = {
    { "GET", "/items/{id:int}", 50, VHTTP_ROUTER_OK },
    { "GET", "/items/{item_id:int}", 51, VHTTP_ROUTER_ERR_CONFLICT },
};

static const vhttp_expect_param_t params_conflict_param_name_0[] = {
    { "id", "1", VHTTP_PARAM_INT },
};

static const vhttp_query_case_t queries_conflict_param_name[] = {
    { "GET", "/items/1", VHTTP_ROUTER_OK, 50, params_conflict_param_name_0, 1 },
};

static const vhttp_route_case_t routes_conflict_param_type[] = {
    { "GET", "/items/{id:int}", 60, VHTTP_ROUTER_OK },
    { "GET", "/items/{id:float}", 61, VHTTP_ROUTER_ERR_CONFLICT },
};

static const vhttp_expect_param_t params_conflict_param_type_0[] = {
    { "id", "2", VHTTP_PARAM_INT },
};

static const vhttp_query_case_t queries_conflict_param_type[] = {
    { "GET", "/items/2", VHTTP_ROUTER_OK, 60, params_conflict_param_type_0, 1 },
};

static const vhttp_route_case_t routes_path_not_last[] = {
    { "GET", "/files/{path:path}/extra", 70, VHTTP_ROUTER_ERR_UNSUPPORTED },
};

static const vhttp_query_case_t queries_path_not_last[] = {
};

static const vhttp_route_case_t routes_invalid_type[] = {
    { "GET", "/bad/{id:bad}", 80, VHTTP_ROUTER_ERR_INVALID },
};

static const vhttp_query_case_t queries_invalid_type[] = {
};

static const vhttp_router_case_t vhttp_router_cases[] = {
    { "static_root", routes_static_root, 1, queries_static_root, 1 },
    { "static_priority", routes_static_priority, 2, queries_static_priority, 2 },
    { "param_int", routes_param_int, 1, queries_param_int, 2 },
    { "param_float", routes_param_float, 1, queries_param_float, 2 },
    { "param_path", routes_param_path, 1, queries_param_path, 1 },
    { "conflict_param_name", routes_conflict_param_name, 2, queries_conflict_param_name, 1 },
    { "conflict_param_type", routes_conflict_param_type, 2, queries_conflict_param_type, 1 },
    { "path_not_last", routes_path_not_last, 1, queries_path_not_last, 0 },
    { "invalid_type", routes_invalid_type, 1, queries_invalid_type, 0 },
};

static const size_t vhttp_router_case_count = sizeof(vhttp_router_cases) / sizeof(vhttp_router_cases[0]);

