#ifndef VHTTP_STATIC_ETAG_TABLE_H
#define VHTTP_STATIC_ETAG_TABLE_H

#include <stddef.h>
#include "vhttp_static_etag.h"

// Auto-generated by tools/gen_static_etags.py; do not edit by hand.
static const vhttp_static_etag_entry_t vhttp_static_etag_table[] = {
    { "large.txt", 9, "W/\"h0be40cf38fc71ded\"", 21 },
};

static const size_t vhttp_static_etag_table_len = 1;

#endif // VHTTP_STATIC_ETAG_TABLE_H
