name: Bug report
description: Report a reproducible defect in ViperHTTP
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: Clear and short description of the observed issue.
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Hardware, firmware, runtime and host environment
      placeholder: |
        Board:
        Port/profile:
        Firmware commit:
        Host OS:
        Python version:
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal deterministic steps
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior and logs
      description: Include traceback, device output, and host tool output.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Performance, stability, security, or functional impact.
