#!/usr/bin/env python3
import argparse
import hashlib
import os
import sys


def c_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("\"", "\\\"")


def iter_files(root: str):
    for dirpath, _, filenames in os.walk(root):
        for name in filenames:
            path = os.path.join(dirpath, name)
            if os.path.isfile(path):
                rel = os.path.relpath(path, root).replace(os.sep, "/")
                yield path, rel


def hash_file(path: str) -> str:
    hasher = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def write_header(out_path: str, entries):
    lines = []
    lines.append("#ifndef VHTTP_STATIC_ETAG_TABLE_H")
    lines.append("#define VHTTP_STATIC_ETAG_TABLE_H")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append('#include "vhttp_static_etag.h"')
    lines.append("")
    lines.append("// Auto-generated by tools/gen_static_etags.py; do not edit by hand.")
    lines.append("static const vhttp_static_etag_entry_t vhttp_static_etag_table[] = {")
    for entry in entries:
        lines.append(
            '    { "%s", %d, "%s", %d },'
            % (
                c_escape(entry["path"]),
                entry["path_len"],
                c_escape(entry["etag"]),
                entry["etag_len"],
            )
        )
    lines.append("};")
    lines.append("")
    lines.append("static const size_t vhttp_static_etag_table_len = %d;" % len(entries))
    lines.append("")
    lines.append("#endif // VHTTP_STATIC_ETAG_TABLE_H")
    lines.append("")

    with open(out_path, "w", newline="\n") as handle:
        handle.write("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--src", required=True, help="Root directory for static assets")
    parser.add_argument("--out", required=True, help="Output header path")
    parser.add_argument("--min-size", type=int, default=16384, help="Minimum size in bytes")
    args = parser.parse_args()

    src = os.path.abspath(args.src)
    if not os.path.isdir(src):
        print(f"Missing static assets directory: {src}", file=sys.stderr)
        return 1

    entries = []
    for path, rel in sorted(iter_files(src), key=lambda item: item[1]):
        size = os.path.getsize(path)
        if size < args.min_size:
            continue
        digest = hash_file(path)[:16]
        etag = f'W/"h{digest}"'
        entries.append(
            {
                "path": rel,
                "path_len": len(rel),
                "etag": etag,
                "etag_len": len(etag),
            }
        )

    write_header(os.path.abspath(args.out), entries)
    print(f"Wrote {len(entries)} ETag entries to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
